Feature/admin
YJorge/TaskManager pull request #17
Opened 2021-05-14 07:43 UTC by YJorge

2021-05-14 18:51 UTC, greybutton requested changes

2021-05-14 18:51 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +    = render partial: "admin/users/form", locals: {user: @user}
получился симпл форм в симпл форме, можно урл передать параметром в _form

2021-05-15 10:31 UTC, YJorge commented on app/controllers/admin/users_controller.rb
> +      render(:new_admin_user_url)
Чувствую себя сумасшедшим . Должно же быть `render(:new)` вместо `render(:new_admin_user_url)`. И что характерно - возникает ошибка при создании нового пользователя, НО одного пользователя я как-то создал с такой записью `render(:new_admin_user_url)`

2021-05-15 17:23 UTC, YJorge commented on app/controllers/admin/users_controller.rb
> +      render(:new_admin_user_url)
В этом ПР уже изменил на `render(:new)`, но всё равно хотелось бы услышать мнение на  вопрос выше

2021-05-17 18:27 UTC, greybutton commented on app/controllers/admin/users_controller.rb
> +      render(:new_admin_user_url)
скорее всего в первый раз код не пошел в else и пользователь создался, а другой раз например валидация не прошла и код пошел в else. Других вариантов не знаю, может еще что то делал и не заметил изменений)

2021-05-17 18:27 UTC, greybutton approved these changes

2021-05-18 17:29 UTC, merged